apiVersion: io.yue9944882.apps/v1
kind: ElasticWorkload
metadata:
  name: elasticworkload-sample
spec:
  spokeNamespace: default
  target:
    type: Inline
    inline:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: nginx-deployment
        namespace: default
        labels:
          app: nginx
      spec:
        replicas: 3
        selector:
          matchLabels:
            app: nginx
        template:
          metadata:
            labels:
              app: nginx
          spec:
            containers:
            - name: nginx
              image: nginx:1.14.2
              ports:
              - containerPort: 80
  placementRef:
    name: my-placement
  distributionStrategy:
    totalReplicas: 10
    type: Even
  budgetStrategy:
    type: None
